### PR TITLE
same changes as snow_api, but with correct github account

### PR DESCRIPTION
**Pull request by bandersen88**
Researched a few different snow forecast APIS (DarkSky, myWeather2, AccuWeather)

- Dark weather gives 7 day forecast, type of precipitation, and precipitation amounts, free for up to 1000 calls per day.  Longest free forecast (Accu weather free to 5 days, paid tier gives 10 and 16)

### CODE REVIEW

**Comment by bandersen88** [comment]
Thoughts so far on firebase incorporation...

Many of the weather api's have very limited free tier access in terms of api calls allowed.  We could use firebase to offset that limitation by making apis calls once per day to pull in the latest forecast info, and then upload that data to firebase, and use firebase for all user access to the data throughout the day.  Users would automatically have new data pushed to their browser from firebase, and could save to local storage, and then all queries against the data would be done locally without consuming api calls.

**Review by eanderson111 — APPROVED** [review]
This looks good, but want to confirm a few things:
1. right now it looks like you're pulling info by resort? is that the approach or proxy for the state?
2. a) we'll be looking at 7 day snow total forecast, or b) report for the LAST 7 day snowfall?

**Comment by bandersen88** [comment]
Yeah I looked at a few different ways and it’s sort of driven off the api. 
The darkski api pulls weather data off latitude and longitude. My hope was to lookup lat and long of every resort and the state and have that stored in forbade. So any state lookup can pull all resort data for that state. 

You supposedly can do a resort lookup by state on several ski resort apis, but they all had issues setting up or werent currently maintained.  Still need to figure that out. 

I can give which state had the highest resort total, if that’s what you mean. There’s probably no state aggregation of snow fall.

Ben

**Comment by bandersen88** [comment]
This one’s 7 day forecast right now. There’s a couple of different options if we want to incorporate current conditions and past snowfall. Haven’t given much thought to that yet.

**Pull request merged**
