### PR TITLE
html and java updates

### PR DESCRIPTION
**Pull request by eanderson111**
I tried to move chart.js info into custom.js but that wasn't working for some reason. So I moved all the custom.js code into my snow.js where I had chart.js and that all worked together. 
Then I continued to use snow.js and added dynamic display of topResorts (it seems there are only 3 not 4?) to the homepage.

I am yet to figure out how to dynamically display images although I did add the image info into the array of resorts. 

And somehow need to figure out how to get the snow total to show up in the charts. If anyone wants to take a look and has any suggestions, I'd welcome them.

### CODE REVIEW

**Comment by bandersen88** [comment]
I'm asking Ian to take a glance at it so he's aware....he's in custom.js working on firebase.  Shouldn't be a problem if we just have to add the updated custom.js code to snow.js, but want to check.

**Comment by eanderson111** [comment]
I am moving on with this code, just FYI. So I"ll probably have more updated version today...

**Comment by bandersen88** [comment]
Do you need me to pull it in?

**Comment by eanderson111** [comment]
Actually, no. I'm coming in with more updated code. The homepage is now fully connected with snow.js which includes everything you had in custom.js. So I'm displaying top resorts, their images and snow fall dynamically.

**Pull request closed without merging**
